version: '3'
services:
  web-socket:
    container_name: web-socket
    restart: always
    image: websocket:latest
#    network_mode: 'host'
    ports:
      - 8081:8081
    volumes:
      - ./config/:/opt/app/config
